// app/page.tsx
 'use client'

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useSession } from 'next-auth/react';
import { Button } from '@/components/ui/button';

export default function Home() {
  const router = useRouter();
  const { data: session, status } = useSession();
  const [imageError, setImageError] = useState(false);

  useEffect(() => {
    if (status === 'authenticated') {
      router.replace('/dashboard');
    }
  }, [router, status]);

  if (session) {
    return null;
  }

  return (
    <main className="relative overflow-hidden">
      <div className="pointer-events-none absolute inset-0 -z-10">
        <div className="absolute -left-32 top-0 h-[36rem] w-[36rem] rounded-full bg-primary/20 blur-3xl" />
        <div className="absolute right-0 top-40 h-[28rem] w-[28rem] rounded-full bg-secondary/20 blur-3xl" />
        <div className="absolute bottom-0 left-1/3 h-[24rem] w-[24rem] rounded-full bg-accent/15 blur-3xl" />
      </div>

      <section className="mx-auto grid max-w-7xl items-center gap-14 px-4 py-14 sm:px-6 lg:grid-cols-2 lg:py-20">
        <div className="space-y-7 lift-in">
          <div className="inline-flex items-center gap-2 rounded-full border border-border/70 bg-card/80 px-3 py-1 text-xs font-medium uppercase tracking-[0.14em] text-muted-foreground">
            Creative Delivery OS
          </div>
          <h1 className="text-4xl font-bold tracking-tight text-foreground sm:text-5xl lg:text-6xl">
            Turn messy client projects into clear, AI-guided execution.
          </h1>
          <p className="max-w-xl text-lg leading-relaxed text-muted-foreground">
            ClientOS gives agencies one professional system for proposals, planning, milestones, status updates, and client approvals.
          </p>

          <div className="flex flex-col gap-3 sm:flex-row">
            <Button asChild size="lg" className="h-12 px-7 text-base">
              <Link href="/login">Start Your Workspace</Link>
            </Button>
            <Button asChild size="lg" variant="outline" className="h-12 px-7 text-base">
              <Link href="/login">See Product Tour</Link>
            </Button>
          </div>

          <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
            <div className="rounded-xl border border-border/60 bg-card/70 p-3">
              <p className="text-2xl font-bold tracking-tight">70%</p>
              <p className="text-xs uppercase tracking-[0.12em] text-muted-foreground">Less status chasing</p>
            </div>
            <div className="rounded-xl border border-border/60 bg-card/70 p-3">
              <p className="text-2xl font-bold tracking-tight">3x</p>
              <p className="text-xs uppercase tracking-[0.12em] text-muted-foreground">Faster scope clarity</p>
            </div>
            <div className="rounded-xl border border-border/60 bg-card/70 p-3">
              <p className="text-2xl font-bold tracking-tight">24/7</p>
              <p className="text-xs uppercase tracking-[0.12em] text-muted-foreground">Client visibility</p>
            </div>
          </div>
        </div>

        <div className="cosmic-panel lift-in rounded-3xl p-6 sm:p-8" style={{ animationDelay: '120ms' }}>
          <div className="mb-5 overflow-hidden rounded-2xl border border-border/60 bg-background/60 p-2">
            {!imageError ? (
              <img
                src="/hero-clientos.svg"
                alt="ClientOS dashboard preview illustration"
                className="h-auto w-full rounded-xl"
                loading="eager"
                onError={() => setImageError(true)}
              />
            ) : (
              <div className="flex h-48 w-full items-center justify-center rounded-xl bg-muted/20 text-sm text-muted-foreground">
                Dashboard preview
              </div>
            )}
          </div>

          <div className="mb-5 flex items-center justify-between rounded-xl border border-border/70 bg-background/70 px-4 py-3">
            <div>
              <p className="text-sm font-medium text-foreground">Live Delivery Board</p>
              <p className="text-xs text-muted-foreground">Real-time timeline + approvals</p>
            </div>
            <span className="rounded-full bg-emerald-500/15 px-2 py-1 text-xs font-medium text-emerald-600 dark:text-emerald-300">
              Healthy
            </span>
          </div>

          <div className="space-y-3">
            <div className="rounded-xl border border-border/60 bg-muted/20 p-4">
              <div className="mb-2 flex items-center justify-between text-sm">
                <p className="font-medium">Proposal approved</p>
                <p className="text-muted-foreground">2h ago</p>
              </div>
              <p className="text-sm text-muted-foreground">Autogenerated project and milestones for BrightLabs website relaunch.</p>
            </div>
            <div className="rounded-xl border border-border/60 bg-muted/20 p-4">
              <div className="mb-2 flex items-center justify-between text-sm">
                <p className="font-medium">GitHub digest published</p>
                <p className="text-muted-foreground">45m ago</p>
              </div>
              <p className="text-sm text-muted-foreground">AI summarized 8 commits into a client-ready milestone update.</p>
            </div>
            <div className="rounded-xl border border-border/60 bg-muted/20 p-4">
              <div className="mb-2 flex items-center justify-between text-sm">
                <p className="font-medium">Client feedback captured</p>
                <p className="text-muted-foreground">12m ago</p>
              </div>
              <p className="text-sm text-muted-foreground">Portal note requested animation timing revisions for checkout flow.</p>
            </div>
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-4 pb-6 sm:px-6">
        <div className="rounded-2xl border border-border/70 bg-card/70 p-6 sm:p-8">
          <p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">Why Teams Choose ClientOS</p>
          <div className="mt-5 grid gap-4 md:grid-cols-3">
            <div className="rounded-xl border border-border/60 bg-background/70 p-4">
              <h3 className="text-lg font-semibold">Proposal to project in one click</h3>
              <p className="mt-2 text-sm text-muted-foreground">Approved proposals instantly become tracked projects with seeded milestones.</p>
            </div>
            <div className="rounded-xl border border-border/60 bg-background/70 p-4">
              <h3 className="text-lg font-semibold">Client-safe communication</h3>
              <p className="mt-2 text-sm text-muted-foreground">Portal-friendly updates keep stakeholders informed without exposing internal noise.</p>
            </div>
            <div className="rounded-xl border border-border/60 bg-background/70 p-4">
              <h3 className="text-lg font-semibold">AI that assists, not distracts</h3>
              <p className="mt-2 text-sm text-muted-foreground">Generate milestone plans and scope checks with actionable output your team can edit.</p>
            </div>
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-4 py-10 sm:px-6">
        <div className="grid gap-6 lg:grid-cols-2">
          <div className="cosmic-panel rounded-2xl p-6 sm:p-7">
            <p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">How It Works</p>
            <ol className="mt-4 space-y-4 text-sm text-muted-foreground">
              <li>
                <span className="mr-2 inline-flex h-6 w-6 items-center justify-center rounded-full bg-primary/15 text-primary">1</span>
                Capture scope and outcomes with AI-assisted planning.
              </li>
              <li>
                <span className="mr-2 inline-flex h-6 w-6 items-center justify-center rounded-full bg-primary/15 text-primary">2</span>
                Turn approved proposals into structured projects with milestones.
              </li>
              <li>
                <span className="mr-2 inline-flex h-6 w-6 items-center justify-center rounded-full bg-primary/15 text-primary">3</span>
                Sync GitHub activity and publish clear updates to clients.
              </li>
              <li>
                <span className="mr-2 inline-flex h-6 w-6 items-center justify-center rounded-full bg-primary/15 text-primary">4</span>
                Gather feedback in one place and keep delivery decisions transparent.
              </li>
            </ol>
          </div>

          <div className="cosmic-panel rounded-2xl p-6 sm:p-7">
            <p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">What You Get</p>
            <div className="mt-4 grid gap-3 sm:grid-cols-2">
              <div className="rounded-xl border border-border/60 bg-background/70 p-4">
                <p className="font-semibold">Role-based auth</p>
                <p className="mt-1 text-sm text-muted-foreground">Agency owners + clients with secure access controls.</p>
              </div>
              <div className="rounded-xl border border-border/60 bg-background/70 p-4">
                <p className="font-semibold">Project board</p>
                <p className="mt-1 text-sm text-muted-foreground">Tasks, scope, settings, and collaboration in one workspace.</p>
              </div>
              <div className="rounded-xl border border-border/60 bg-background/70 p-4">
                <p className="font-semibold">Client portal</p>
                <p className="mt-1 text-sm text-muted-foreground">Milestones, progress, deliverables, and feedback threads.</p>
              </div>
              <div className="rounded-xl border border-border/60 bg-background/70 p-4">
                <p className="font-semibold">Automation hooks</p>
                <p className="mt-1 text-sm text-muted-foreground">GitHub events and AI summaries keep updates flowing.</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-4 pb-8 pt-2 sm:px-6 sm:pb-12">
        <div className="rounded-2xl border border-border/60 bg-gradient-to-r from-primary/15 via-secondary/10 to-accent/15 p-8 text-center">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Build client trust through better delivery design.</h2>
          <p className="mx-auto mt-3 max-w-2xl text-muted-foreground">
            Create your workspace and start running projects with a cleaner, more transparent operational system.
          </p>
          <div className="mt-6 flex flex-col justify-center gap-3 sm:flex-row">
            <Button asChild size="lg" className="h-12 px-7">
              <Link href="/login">Launch ClientOS</Link>
            </Button>
            <Button asChild size="lg" variant="outline" className="h-12 px-7">
              <Link href="/proposals/new">Create a Proposal</Link>
            </Button>
          </div>
        </div>
      </section>
    </main>
  );
}
